language: go
go:
  - "1.10"
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
before_script:
  - git clone --depth=50 --branch=master https://github.com/chenhg5/go-admin.git /home/travis/gopath/src/goAdmin
  - cd /home/travis/gopath/src/goAdmin
  - mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - mysql -e 'CREATE DATABASE IF NOT EXISTS godmin;'
  - mysql -u root --default-character-set=utf8mb4 godmin < admin.sql
  - make deps
script:
  - make test