language: go
sudo: false

go:
  - 1.12.x

env:
  - GO111MODULE=on PGPASSWORD=root

services:
  - mysql
  - postgresql

before_install:
  - mysql -e 'create database `go-admin-test`;'
  - createdb -U postgres go-admin-test

before_script:
  - echo "USE mysql;\nUPDATE user SET authentication_string=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - psql -c "ALTER USER postgres WITH PASSWORD 'root';" -U postgres

script:
  - cd /home/travis/gopath/src/github.com/chenhg5/go-admin && make deps
  - make test
