language: go
sudo: false

go:
  - 1.12.x

services:
  - mysql

before_install:
  - mysql -e 'create database `go-admin-test`;'

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - git clone --depth=50 --branch=master https://github.com/chenhg5/go-admin.git  /home/travis/gopath/src/go-admin

script:
  - cd /home/travis/gopath/src/go-admin && make deps
  - make test
