language: go
sudo: false

go:
  - 1.12.x

services:
  - mysql

before_install:
  - mysql -e 'create database `go-admin-test`;'

before_script:
  - echo "USE mysql;\nUPDATE user SET authentication_string=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - go get -u -v github.com/chenhg5/go-admin

script:
  - ls /home/travis/gopath/pkg/mod
  - cd /home/travis/gopath/src/github.com/chenhg5/go-admin && make deps
  - make test
